import type { LocalizedText } from '@ready/content-schema';
import type { GameWord, GameWordSource } from '../../features/games/types.js';

/**
 * Core 100 loader (Core Words + games data source).
 *
 * Loads the offline pack `public/content/core-en.v1.json` — GENERATED by the content pipeline
 * from the canonical concepts (content/concepts/core-en.yaml), the same source seeded to Mongo.
 * The pack is PWA-precached, so after first load the app reads it fully offline. This replaces the
 * old React mock as the production game source; the mock stays only for isolated unit tests.
 */

export interface CoreWord {
  id: string;                 // en.word.slug
  conceptId: string;          // concept.word.slug
  word: string;               // English realization
  meaning: LocalizedText;     // gloss (en + he)
  emoji: string;
  category: string;
  tier: number;
  rank: number;
  skill: string;
  example?: LocalizedText;
}

interface CorePack {
  lang: string;
  version: string;
  count: number;
  words: CoreWord[];
}

/** Resolve a public path against the app base (dev, deployed sub-path, PWA all work). */
function resolveAsset(src: string): string {
  const base = (import.meta.env.BASE_URL || '/').replace(/\/$/, '');
  return src.startsWith('/') ? base + src : `${base}/${src}`;
}

let cache: Promise<CoreWord[]> | null = null;

/** Fetch + cache the Core 100 (once). Never throws — a failure yields an empty list so the UI
 *  shows an honest empty state instead of crashing (offline-first). */
export function loadCoreWords(): Promise<CoreWord[]> {
  if (!cache) {
    cache = fetch(resolveAsset('/content/core-en.v1.json'))
      .then((r) => (r.ok ? (r.json() as Promise<CorePack>) : Promise.reject(new Error(`HTTP ${r.status}`))))
      .then((pack) => pack.words.slice().sort((a, b) => a.rank - b.rank))
      .catch((err) => {
        console.warn('[coreWords] pack unavailable — Core Words empty until content is built', err);
        cache = null; // allow a later retry
        return [];
      });
  }
  return cache;
}

/** Adapt Core words → the generic GameWord shape both games consume. */
export function toGameWords(words: CoreWord[]): GameWord[] {
  return words.map((w) => ({
    id: w.id,
    word: w.word,
    translation: w.meaning,
    emoji: w.emoji,
  }));
}

/** A GameWordSource backed by the real Core 100 (the seam the games were designed against). */
export function coreWordSource(words: CoreWord[]): GameWordSource {
  return {
    id: 'core-en-100',
    title: { en: 'Core 100', he: 'ליבה 100' },
    words: () => toGameWords(words),
  };
}

/** Distinct categories in load order (for grouping the Browse list). */
export function coreCategories(words: CoreWord[]): string[] {
  const seen: string[] = [];
  for (const w of words) if (!seen.includes(w.category)) seen.push(w.category);
  return seen;
}
