import type { LocalizedText } from '@ready/content-schema';
import type { GameWord, GameWordSource } from '../../features/games/types.js';

/**
 * Core Corpus loader (Core Words + games data source).
 *
 * Loads the offline pack `public/content/core-{lang}.v1.json` — GENERATED by the content
 * pipeline from the canonical concepts (content/concepts/core-corpus.yaml), the same source
 * seeded to Mongo. Packs are PWA-precached, so after first load the app reads them fully
 * offline. Language-parameterized: a future French pilot loads `core-fr.v1.json` through this
 * exact function — no code change, only content (see docs/CORE-CORPUS.md).
 */

export interface CoreWord {
  id: string;                 // {lang}.{kind}.{slug}
  conceptId: string;          // concept.{kind}.{slug}
  word: string;               // target-language realization
  meaning: LocalizedText;     // gloss (en + he)
  emoji?: string;             // present only for icon-eligible concepts (game words)
  category: string;
  pos: string;
  tier: number;
  rank: number;
  skill: string;
  example?: LocalizedText;
}

interface CorePack {
  lang: string;
  version: string;
  count: number;
  words: CoreWord[];
}

/** Resolve a public path against the app base (dev, deployed sub-path, PWA all work). */
function resolveAsset(src: string): string {
  const base = (import.meta.env.BASE_URL || '/').replace(/\/$/, '');
  return src.startsWith('/') ? base + src : `${base}/${src}`;
}

const cache = new Map<string, Promise<CoreWord[]>>();

/** Fetch + cache the Core pack for a language (once per language). Never throws — a failure
 *  yields an empty list so the UI shows an honest empty state instead of crashing. */
export function loadCoreWords(lang = 'en'): Promise<CoreWord[]> {
  let hit = cache.get(lang);
  if (!hit) {
    hit = fetch(resolveAsset(`/content/core-${lang}.v1.json`))
      .then((r) => (r.ok ? (r.json() as Promise<CorePack>) : Promise.reject(new Error(`HTTP ${r.status}`))))
      .then((pack) => pack.words.slice().sort((a, b) => a.rank - b.rank))
      .catch((err) => {
        console.warn(`[coreWords] core-${lang} pack unavailable — Core Words empty until content is built`, err);
        cache.delete(lang); // allow a later retry
        return [];
      });
    cache.set(lang, hit);
  }
  return hit;
}

/** Adapt Core words → the generic GameWord shape. The emoji games consume only icon-eligible
 *  words (unique emoji per concept — the quiz distractor invariant); non-visual words stay in
 *  Browse and await text-first games. */
export function toGameWords(words: CoreWord[]): GameWord[] {
  return words
    .filter((w): w is CoreWord & { emoji: string } => !!w.emoji)
    .map((w) => ({
      id: w.id,
      word: w.word,
      translation: w.meaning,
      emoji: w.emoji,
    }));
}

/** A GameWordSource backed by the real Core Corpus (the seam the games were designed against). */
export function coreWordSource(words: CoreWord[]): GameWordSource {
  return {
    id: 'core-corpus',
    title: { en: 'Core Words', he: 'מילות הליבה' },
    words: () => toGameWords(words),
  };
}

/** Distinct categories in rank order (for grouping the Browse list). */
export function coreCategories(words: CoreWord[]): string[] {
  const seen: string[] = [];
  for (const w of words) if (!seen.includes(w.category)) seen.push(w.category);
  return seen;
}
