import type { LocalizedText } from '@ready/content-schema';

/**
 * The READY Bootcamp — 20 real-world capabilities, not 20 lessons (Sprint 6 Part 1).
 * Each day exists to retire one fear and to hand the next day its prerequisites.
 * Day 1 is fully built; days 2–20 are planned here and built as content files later.
 */

export interface BootcampDayPlan {
  day: number;
  title: LocalizedText;          // the capability, first person: "I can survive."
  objective: LocalizedText;
  confidenceGain: LocalizedText; // what fear shrinks today
  situations: string[];
  targets: { concepts: number; phrases: number; dialogues: number };
  listeningSkill: string;
  speakingSkill: string;
  minutes: number;
  feeling: LocalizedText;        // expected completion feeling
  why: string;                   // why this day exists
  preparesNext: string;          // what it hands to the next day
}

export const BOOTCAMP_PLAN: BootcampDayPlan[] = [
  { day: 1, title: { en: 'I can survive.', he: 'אני יכול לשרוד.' },
    objective: { en: 'Own the 7 survival tools — you can never be stuck again.', he: 'לשלוט בשבעת כלי ההישרדות — אי אפשר יותר להיתקע.' },
    confidenceGain: { en: 'The fear of freezing dies first.', he: 'הפחד מלקפוא נעלם ראשון.' },
    situations: ['recovery'], targets: { concepts: 7, phrases: 7, dialogues: 1 },
    listeningSkill: 'recognize the 7 tools at natural speed', speakingSkill: 'say each tool aloud once',
    minutes: 20, feeling: { en: "I still don't know English — but I'm less afraid.", he: 'אני עדיין לא יודע אנגלית — אבל אני כבר פחות מפחד.' },
    why: 'Recoverability before vocabulary: the safety net IS the confidence.',
    preparesNext: 'Every later dialogue assumes the tools are reflexes.' },
  { day: 2, title: { en: 'I can introduce myself.', he: 'אני יכול להציג את עצמי.' },
    objective: { en: 'Name, origin, purpose — delivered with confidence.', he: 'שם, מאיפה, למה — בביטחון.' },
    confidenceGain: { en: 'First human connection.', he: 'חיבור אנושי ראשון.' },
    situations: ['social'], targets: { concepts: 8, phrases: 5, dialogues: 1 },
    listeningSkill: "understand 'Where are you from?' variants", speakingSkill: 'the My-name opener to performance level',
    minutes: 20, feeling: { en: 'People can know me.', he: 'אפשר להכיר אותי.' },
    why: 'Identity phrases are the highest-warmth, lowest-risk production.',
    preparesNext: 'The opener habit (prosody-first) used every day after.' },
  { day: 3, title: { en: 'I can buy a coffee.', he: 'אני יכול לקנות קפה.' },
    objective: { en: 'Complete a real counter transaction end-to-end.', he: 'לסגור עסקת דלפק אמיתית מההתחלה עד הסוף.' },
    confidenceGain: { en: 'First full transaction.', he: 'עסקה שלמה ראשונה.' },
    situations: ['restaurant'], targets: { concepts: 8, phrases: 5, dialogues: 1 },
    listeningSkill: "'For here or to go?' at speed", speakingSkill: "I'd-like template with 3 fillers",
    minutes: 20, feeling: { en: 'I ordered. It worked.', he: 'הזמנתי. זה עבד.' },
    why: 'The canonical First Move abroad — small, daily, winnable.',
    preparesNext: 'The order template that scales to full meals (day 5).' },
  { day: 4, title: { en: 'I can understand prices.', he: 'אני מבין מחירים.' },
    objective: { en: 'Numbers 1–100 by ear, money answers at speed.', he: 'מספרים בשמיעה ותשובות כסף במהירות.' },
    confidenceGain: { en: 'No more nodding at unknown totals.', he: 'לא מהנהנים יותר בלי להבין את הסכום.' },
    situations: ['paying'], targets: { concepts: 14, phrases: 3, dialogues: 1 },
    listeningSkill: "'That'll be twenty…' number extraction", speakingSkill: 'How-much question',
    minutes: 20, feeling: { en: 'Money makes sense now.', he: 'הכסף כבר מובן.' },
    why: 'Numbers are the single highest-frequency comprehension task abroad.',
    preparesNext: 'Every payment moment in days 5–20.' },
  { day: 5, title: { en: 'I can order a meal.', he: 'אני יכול להזמין ארוחה.' },
    objective: { en: 'Restaurant end-to-end: table → order → bill.', he: 'מסעדה מקצה לקצה: שולחן → הזמנה → חשבון.' },
    confidenceGain: { en: 'The emotional heart of travel, survived.', he: 'לב הטיול — שרדנו.' },
    situations: ['restaurant'], targets: { concepts: 10, phrases: 6, dialogues: 2 },
    listeningSkill: 'waiter script: drink/order/anything-else', speakingSkill: 'table opener + without-template',
    minutes: 20, feeling: { en: 'Dinner is mine.', he: 'ארוחת ערב זה שלי.' },
    why: '3–5 restaurant interactions happen per travel day.',
    preparesNext: 'Allergy/diet operator reused in day 13.' },
  { day: 6, title: { en: 'I can ask for directions.', he: 'אני יכול לשאול לכיוונים.' },
    objective: { en: 'Ask, then actually understand the answer.', he: 'לשאול — ובעיקר להבין את התשובה.' },
    confidenceGain: { en: 'Being lost stops being scary.', he: 'ללכת לאיבוד מפסיק להפחיד.' },
    situations: ['directions'], targets: { concepts: 9, phrases: 4, dialogues: 1 },
    listeningSkill: 'left/right/straight + landmark answers', speakingSkill: 'How-do-I-get template',
    minutes: 20, feeling: { en: 'The city opened up.', he: 'העיר נפתחה.' },
    why: 'Directions are 90% listening — the anti-freeze muscle in its purest form.',
    preparesNext: 'Spatial replies feed taxi (7) and transit (14).' },
  { day: 7, title: { en: 'I can take a taxi.', he: 'אני יכול לקחת מונית.' },
    objective: { en: 'Destination, price, stop — with the address-show move.', he: 'יעד, מחיר, עצירה — כולל מהלך הצגת הכתובת.' },
    confidenceGain: { en: 'Doors of any city unlocked.', he: 'כל עיר נהיית נגישה.' },
    situations: ['taxi'], targets: { concepts: 6, phrases: 4, dialogues: 1 },
    listeningSkill: 'driver smalltalk + price', speakingSkill: 'To-this-address opener',
    minutes: 20, feeling: { en: 'I can get anywhere.', he: 'אני יכול להגיע לכל מקום.' },
    why: 'Taxi is the highest-stakes 60-second conversation of day one abroad.',
    preparesNext: 'Authority-adjacent confidence for passport day (8).' },
  { day: 8, title: { en: 'I can pass passport control.', he: 'אני יכול לעבור ביקורת דרכונים.' },
    objective: { en: 'The 4 border questions, answered calmly.', he: 'ארבע שאלות הגבול — בקור רוח.' },
    confidenceGain: { en: 'Authority stops being frightening.', he: 'סמכות מפסיקה להפחיד.' },
    situations: ['border'], targets: { concepts: 6, phrases: 4, dialogues: 1 },
    listeningSkill: 'purpose/duration/where-staying variants', speakingSkill: 'trip + nights answers',
    minutes: 20, feeling: { en: 'Borders are just a script.', he: 'גבול זה בסך הכל תסריט.' },
    why: 'The scariest moment with the most predictable script — perfect ROI.',
    preparesNext: 'Calm-under-authority reused in emergencies (17).' },
  { day: 9, title: { en: 'I can check into a hotel.', he: "אני יכול לעשות צ'ק-אין במלון." },
    objective: { en: 'Reservation → name → key → breakfast info.', he: 'הזמנה → שם → מפתח → פרטי ארוחת בוקר.' },
    confidenceGain: { en: 'Home base secured.', he: 'בסיס הבית מובטח.' },
    situations: ['hotel'], targets: { concepts: 8, phrases: 5, dialogues: 1 },
    listeningSkill: 'floor/breakfast/time comprehension', speakingSkill: 'reservation opener',
    minutes: 20, feeling: { en: 'I belong here.', he: 'אני שייך לכאן.' },
    why: 'Check-in is trip-start concentrated — nail it once, relax all week.',
    preparesNext: 'Completes the arrival trio (taxi→border→hotel) for day 10.' },
  { day: 10, title: { en: 'I can survive my first day abroad.', he: 'אני שורד יום ראשון בחו"ל.' },
    objective: { en: 'Midpoint integration: arrival-day moments chained, first cold opens.', he: 'אינטגרציה: שרשור רגעי יום ההגעה + קולד-אופנים ראשונים.' },
    confidenceGain: { en: 'Proof: the whole arrival day is survivable.', he: 'הוכחה: יום הגעה שלם — שריד.' },
    situations: ['taxi', 'border', 'hotel', 'restaurant'], targets: { concepts: 0, phrases: 0, dialogues: 3 },
    listeningSkill: 'first unannounced (cold) triggers', speakingSkill: 'chained openers',
    minutes: 20, feeling: { en: 'Half-way, and already functional.', he: 'חצי דרך — וכבר מתפקדים.' },
    why: 'Consolidation day: no new content, pure survival evidence (receipts).',
    preparesNext: 'Cold-open format used from here on.' },
  { day: 11, title: { en: 'I can shop and pay.', he: 'אני יכול לקנות ולשלם.' },
    objective: { en: 'Browse, ask, decide, pay — politely and in control.', he: 'להסתובב, לשאול, להחליט, לשלם — בנימוס ובשליטה.' },
    confidenceGain: { en: 'Shops become friendly territory.', he: 'חנויות נהיות טריטוריה ידידותית.' },
    situations: ['paying'], targets: { concepts: 8, phrases: 5, dialogues: 1 },
    listeningSkill: 'can-I-help/size/receipt questions', speakingSkill: 'just-looking + take-it',
    minutes: 20, feeling: { en: 'I shop like a person, not a mime.', he: 'קונים כמו בן אדם, לא בפנטומימה.' },
    why: 'High-frequency, low-stakes reps that cement the payment loop from day 4.',
    preparesNext: 'Decision phrases reused in problem day (15).' },
  { day: 12, title: { en: 'I can understand fast replies.', he: 'אני מבין תשובות מהירות.' },
    objective: { en: 'Listening bootcamp: all learned replies at full speed, no slow button.', he: 'אימון שמיעה: כל התשובות במהירות מלאה, בלי כפתור האטה.' },
    confidenceGain: { en: 'Native speed stops being noise.', he: 'מהירות טבעית מפסיקה להיות רעש.' },
    situations: ['all'], targets: { concepts: 0, phrases: 0, dialogues: 2 },
    listeningSkill: 'full-speed comprehension across situations', speakingSkill: 'none — ears day',
    minutes: 20, feeling: { en: 'I hear words now, not blur.', he: 'אני שומע מילים, לא מריחה.' },
    why: 'Dedicated desirable-difficulty day; the #1 traveler failure is the reply.',
    preparesNext: 'Speed baseline required for cold-heavy days 18–20.' },
  { day: 13, title: { en: 'I can handle a pharmacy visit.', he: 'אני מסתדר בבית מרקחת.' },
    objective: { en: 'Symptoms, allergies, medicine — clearly and safely.', he: 'תסמינים, אלרגיות, תרופות — ברור ובטוח.' },
    confidenceGain: { en: 'Health needs stop being terrifying abroad.', he: 'צרכים רפואיים מפסיקים להפחיד בחו"ל.' },
    situations: ['medical'], targets: { concepts: 9, phrases: 5, dialogues: 1 },
    listeningSkill: 'dosage/instructions comprehension', speakingSkill: 'allergic + pain reporters',
    minutes: 20, feeling: { en: 'My body is safe here too.', he: 'גם הגוף שלי בטוח כאן.' },
    why: 'RoF-3 content: rare but catastrophic to lack.',
    preparesNext: 'Safety phrases feed emergency day (17).' },
  { day: 14, title: { en: 'I can ride public transport.', he: 'אני מסתדר בתחבורה ציבורית.' },
    objective: { en: 'Tickets, platforms, stops — without panic.', he: 'כרטיסים, רציפים, תחנות — בלי פאניקה.' },
    confidenceGain: { en: 'The cheap, local way to move is now mine.', he: 'הדרך המקומית והזולה לנוע — שלי.' },
    situations: ['transport'], targets: { concepts: 8, phrases: 4, dialogues: 1 },
    listeningSkill: 'platform/direction announcements', speakingSkill: 'ticket + does-it-stop',
    minutes: 20, feeling: { en: 'I move like a local.', he: 'אני זז כמו מקומי.' },
    why: 'Unlocks independence beyond taxi budgets.',
    preparesNext: 'Announcement-listening primes day 18.' },
  { day: 15, title: { en: 'I can fix a problem.', he: 'אני יכול לפתור בעיה.' },
    objective: { en: 'Wrong order, wrong charge, wrong room — resolved with grace.', he: 'הזמנה שגויה, חיוב שגוי, חדר שגוי — נפתרים באלגנטיות.' },
    confidenceGain: { en: 'Friction stops meaning failure.', he: 'תקלה מפסיקה להיות כישלון.' },
    situations: ['all'], targets: { concepts: 6, phrases: 5, dialogues: 2 },
    listeningSkill: 'apology/solution replies', speakingSkill: 'polite complaint + recovery chains',
    minutes: 20, feeling: { en: 'Things go wrong. I go right.', he: 'דברים משתבשים. אני לא.' },
    why: 'Recovery under real friction — the Day-1 kit graduating to full scenes.',
    preparesNext: 'The designed-breakdown format used in rehearsals.' },
  { day: 16, title: { en: 'I can make small talk.', he: 'אני יכול לנהל שיחת חולין.' },
    objective: { en: 'Three minutes of warm human conversation.', he: 'שלוש דקות של שיחה אנושית חמה.' },
    confidenceGain: { en: 'Connection, not just transactions.', he: 'חיבור, לא רק עסקאות.' },
    situations: ['social'], targets: { concepts: 8, phrases: 5, dialogues: 1 },
    listeningSkill: 'follow-up questions', speakingSkill: 'family/trip/compliments',
    minutes: 20, feeling: { en: 'I made someone smile in English.', he: 'הצחקתי מישהו באנגלית.' },
    why: 'The enjoyment layer — trips are remembered by these minutes.',
    preparesNext: 'Free-flow confidence for the final days.' },
  { day: 17, title: { en: 'I can handle an emergency.', he: 'אני יכול להתמודד עם חירום.' },
    objective: { en: 'Help, doctor, police, lost items — automatic under stress.', he: 'עזרה, רופא, משטרה, אבידות — אוטומטית תחת לחץ.' },
    confidenceGain: { en: 'The worst case has a script now.', he: 'גם לתרחיש הגרוע יש תסריט.' },
    situations: ['emergency'], targets: { concepts: 7, phrases: 5, dialogues: 1 },
    listeningSkill: 'responder questions', speakingSkill: 'overlearned emergency set (timed)',
    minutes: 20, feeling: { en: 'Whatever happens, I can act.', he: 'שיקרה מה שיקרה — אני אפעל.' },
    why: 'Under real stress only automatic memory survives; trained late so it sticks fresh.',
    preparesNext: 'Completes the safety floor under the final exam.' },
  { day: 18, title: { en: 'I can understand without subtitles.', he: 'אני מבין בלי כתוביות.' },
    objective: { en: 'Training wheels off: all dialogues, no text, variant forms.', he: 'בלי גלגלי עזר: כל הדיאלוגים בלי טקסט, כולל וריאציות.' },
    confidenceGain: { en: 'My ears stand alone.', he: 'האוזניים עומדות בפני עצמן.' },
    situations: ['all'], targets: { concepts: 0, phrases: 0, dialogues: 3 },
    listeningSkill: 'no-subtitle comprehension + surprise variants', speakingSkill: 'reply under uncertainty',
    minutes: 20, feeling: { en: 'I trust my ears.', he: 'אני סומך על האוזניים שלי.' },
    why: 'Visible removal of support is itself proof (receipt-worthy).',
    preparesNext: 'Cold format for the rehearsal.' },
  { day: 19, title: { en: 'I can handle a full evening out.', he: 'אני עומד בערב שלם בחוץ.' },
    objective: { en: 'Dress rehearsal: taxi → restaurant → problem → payment, one take.', he: 'חזרה גנרלית: מונית → מסעדה → תקלה → תשלום, בטייק אחד.' },
    confidenceGain: { en: 'Chained moments feel like one easy flow.', he: 'רצף רגעים מרגיש כמו זרימה אחת קלה.' },
    situations: ['taxi', 'restaurant', 'paying'], targets: { concepts: 0, phrases: 0, dialogues: 4 },
    listeningSkill: 'continuous, mixed-situation', speakingSkill: 'sustained production, one take',
    minutes: 20, feeling: { en: 'That was… almost fun?', he: 'זה היה… כמעט כיף?' },
    why: 'The athlete’s rehearsal before race day; one designed surprise included.',
    preparesNext: 'The final exam format.' },
  { day: 20, title: { en: 'I can spend a whole day abroad alone.', he: 'אני יכול לבלות יום שלם לבד בחו"ל.' },
    objective: { en: 'Graduation: morning-to-night cold moment chain. One take. Real verdict.', he: 'סיום: שרשרת רגעים קרים מבוקר עד לילה. טייק אחד. פסק דין אמיתי.' },
    confidenceGain: { en: 'Independence, proven.', he: 'עצמאות — מוכחת.' },
    situations: ['all'], targets: { concepts: 0, phrases: 0, dialogues: 5 },
    listeningSkill: 'everything, cold', speakingSkill: 'everything, cold',
    minutes: 25, feeling: { en: "I'm ready. Actually ready.", he: 'אני מוכן. באמת מוכן.' },
    why: 'The finish line must be an experience, not a certificate.',
    preparesNext: 'Real life. The First Move abroad.' },
];
