/**
 * French Foundation example sentences — AUTHORED French, one per Foundation building-block concept.
 *
 * The Core Corpus stores examples per concept in en+he only, so a French learner would otherwise see
 * an English example on a Foundation word page (immersion-breaking). Each entry here is the FRENCH
 * translation of that concept's canonical example, so the corpus Hebrew (`example.he`) stays aligned
 * as the "underneath" line and the word page reads: French first · Hebrew under · French audio.
 *
 * Keyed by language-independent concept id (works for the tapped word and the browsed word alike).
 * AI-drafted, neutral-polite (vous), `pending native review` — consistent with the French Bootcamp.
 *
 * This file is pure CONTENT (a French map). The language-agnostic accessor lives in
 * `foundationExamples.ts`, which registers this map under `fr` — so adding another language's
 * examples is content-only, with no per-language code branch. When a concept has no entry, the app
 * shows the app-language meaning (never English-as-French).
 */
export const FRENCH_EXAMPLES: Record<string, string> = {
  // ⚡ Essential verbs
  'concept.word.help': 'Pouvez-vous m’aider ?',
  'concept.word.stop': 'Arrêtez-vous ici, s’il vous plaît.',
  'concept.word.lose': 'J’ai perdu mon passeport.',
  'concept.word.want': 'Je veux celui-ci.',
  'concept.word.need': 'J’ai besoin d’aide.',
  'concept.word.have': 'J’ai une réservation.',
  'concept.word.go': 'Nous allons à l’aéroport.',
  'concept.word.speak': 'Parlez-vous anglais ?',
  'concept.word.pay': 'Je peux payer par carte ?',
  'concept.word.understand': 'Maintenant, je comprends.',
  'concept.word.eat': 'Où peut-on manger ?',
  'concept.word.can': 'Pouvez-vous m’aider ?',
  'concept.word.order': 'Vous êtes prêt à commander ?',
  'concept.word.wait': 'Attendez ici, s’il vous plaît.',
  'concept.word.show': 'Pouvez-vous me montrer ?',
  'concept.word.turn': 'Tournez à gauche au coin.',
  'concept.word.take': 'Je vais le prendre.',
  'concept.word.buy': 'Où puis-je acheter des billets ?',
  'concept.word.come': 'Venez avec moi, s’il vous plaît.',
  'concept.word.call': 'Appelez un taxi, s’il vous plaît.',
  'concept.word.find': 'Je ne trouve pas mon hôtel.',
  'concept.word.leave': 'Le train part à neuf heures.',
  'concept.word.book': 'J’ai réservé une chambre.',
  'concept.word.arrive': 'Quand est-ce qu’il arrive ?',
  'concept.word.drink': 'Quelque chose à boire ?',
  'concept.word.know': 'Vous connaissez un bon endroit ?',
  'concept.word.give': 'Donnez-m’en un, s’il vous plaît.',
  'concept.word.work': 'La douche ne marche pas.',
  'concept.word.cancel': 'Je veux annuler la commande.',
  'concept.word.fly': 'Nous prenons l’avion dimanche.',
  'concept.word.rent': 'Nous voulons louer une voiture.',
  'concept.word.exchange': 'Où puis-je changer de l’argent ?',
  'concept.word.forget': 'J’ai oublié ma clé.',
  'concept.word.break': 'C’est cassé.',
  'concept.word.smoke': 'Interdit de fumer ici.',
  'concept.word.stay': 'Nous restons trois nuits.',
  'concept.word.see': 'Je voudrais voir le menu.',
  'concept.word.look': 'Regardez ça !',
  'concept.word.say': 'Comment dit-on ça ?',
  'concept.word.like': 'J’aime bien cet endroit.',
  'concept.word.get': 'Où prend-on le bus ?',
  'concept.word.ask': 'Demandons à quelqu’un.',
  'concept.word.use': 'Je peux utiliser le téléphone ?',
  'concept.word.return': 'Nous revenons demain.',
  'concept.word.push': 'Poussez la porte.',
  'concept.word.pull': 'Tirez, ne poussez pas.',
  'concept.word.sit': 'On peut s’asseoir dehors ?',
  'concept.word.try': 'Je peux l’essayer ?',
  'concept.word.love': 'J’adore cette ville.',
  'concept.word.bring': 'Pouvez-vous apporter l’addition ?',
  'concept.word.visit': 'Nous voulons visiter la vieille ville.',
  'concept.word.travel': 'Nous voyageons beaucoup.',
  'concept.word.think': 'Je pense que c’est près.',
  'concept.word.hear': 'Je ne vous entends pas.',
  'concept.word.sleep': 'J’ai besoin de dormir.',
  'concept.word.answer': 'Personne ne répond.',
  'concept.word.remember': 'Je ne me souviens pas du nom.',
  'concept.word.send': 'Envoyez-moi l’adresse.',
  'concept.word.drive': 'Il conduit lentement.',
  'concept.word.meet': 'Ravi de vous rencontrer.',
  'concept.word.stand': 'Faites la queue, s’il vous plaît.',
  'concept.word.wash': 'Où puis-je me laver les mains ?',
  'concept.word.play': 'Les enfants jouent dans le parc.',
  'concept.word.read': 'Je lis un livre.',
  'concept.word.write': 'Écrivez votre nom, s’il vous plaît.',
  'concept.word.cook': 'Ma mère cuisine une soupe.',
  'concept.word.wear': 'Je porte une veste en hiver.',
  'concept.word.build': 'Ils construisent une maison.',
  'concept.word.sing': 'Les oiseaux chantent chaque matin.',

  // 🎨 Colors
  'concept.word.red': 'Le bus rouge.',
  'concept.word.blue': 'La ligne bleue.',
  'concept.word.green': 'Traversez au vert.',
  'concept.word.black': 'Un café noir, s’il vous plaît.',
  'concept.word.white': 'Du vin blanc.',
  'concept.word.pink': 'La robe rose.',
  'concept.word.yellow': 'Le taxi jaune.',
  'concept.word.orange': 'Le bâtiment orange.',
  'concept.word.brown': 'Le sac marron.',
  'concept.word.purple': 'La ligne violette.',

  // 📏 Quantity
  'concept.word.more': 'Un peu plus, s’il vous plaît.',
  'concept.word.full': 'L’hôtel est plein.',
  'concept.word.less': 'Un peu moins, s’il vous plaît.',
  'concept.word.empty': 'Le bus est vide.',

  // 📍 Position & Direction
  'concept.word.here': 'Arrêtez-vous ici, s’il vous plaît.',
  'concept.word.left': 'C’est à gauche.',
  'concept.word.right': 'Tournez à droite.',
  'concept.word.there': 'C’est là-bas.',
  'concept.word.up': 'La chambre est en haut de l’escalier.',
  'concept.word.down': 'Le petit-déjeuner est en bas.',

  // 🔗 Connectors & ✅ Quick responses (glue)
  'concept.word.yes': 'Oui, s’il vous plaît.',
  'concept.word.no': 'Non, merci.',
  'concept.word.please': 'Un billet, s’il vous plaît.',
  'concept.word.okay': 'D’accord, pas de problème.',
  'concept.word.hello': 'Bonjour ! Une table pour deux ?',
  'concept.reply.here-you-go': '« Voilà. » — « Merci ! »',
  'concept.phrase.excuse-me': 'Excusez-moi, où est la sortie ?',
  'concept.word.with': 'Un café avec du lait.',
  'concept.word.and': 'Un café et de l’eau.',
  'concept.word.or': 'Espèces ou carte ?',
  'concept.word.without': 'Un thé sans sucre.',
  'concept.reply.i-dont-know': 'Je ne sais pas. Demandons.',
  'concept.word.goodbye': 'Au revoir, et merci !',
  'concept.reply.sounds-good': '« Une pizza ce soir ? » — « Ça marche ! »',
  'concept.reply.no-worries': '« Désolé, nous sommes en retard. » — « Pas de souci. »',
  'concept.reply.thats-fine': '« Carte seulement, pas d’espèces. » — « C’est bon. »',
  'concept.reply.no-problem': '« On peut payer séparément ? » — « Pas de problème. »',
  'concept.reply.never-mind': 'Laissez tomber, merci quand même.',
  'concept.reply.im-not-sure': 'Je ne suis pas sûr. Peut-être à neuf heures.',
  'concept.reply.thats-all': '« Autre chose ? » — « C’est tout, merci. »',
  'concept.reply.one-more': 'Encore un, s’il vous plaît. C’était très bon.',
  'concept.word.enough': 'Ça suffit, merci.',
  'concept.reply.just-looking': '« Je peux vous aider ? » — « Je regarde seulement. »',
  'concept.reply.to-go': 'Un café à emporter, s’il vous plaît.',
  'concept.word.great': 'Super, merci !',
  'concept.reply.youre-welcome': '« Merci ! » — « Je vous en prie. »',
  'concept.reply.of-course': '« Je peux m’asseoir ici ? » — « Bien sûr. »',
  'concept.reply.have-a-nice-day': '« Bonne journée ! » — « Vous aussi ! »',
  'concept.phrase.good-morning': 'Bonjour ! Le petit-déjeuner, s’il vous plaît.',
  'concept.reply.lets-go': 'Le taxi est là. Allons-y !',
  'concept.phrase.good-evening': 'Bonsoir ! Nous avons une réservation.',
  'concept.reply.maybe-later': '« Un dessert ? » — « Peut-être plus tard. »',
  'concept.reply.go-ahead': '« Je peux demander quelque chose ? » — « Allez-y. »',
  'concept.word.really': 'Vraiment ? C’est génial !',
  'concept.reply.take-your-time': '« Une minute… » — « Prenez votre temps. »',
  'concept.reply.me-too': '« J’adore cette ville. » — « Moi aussi ! »',
  'concept.reply.and-you': 'Je vais bien. Et vous ?',
  'concept.reply.see-you-later': 'À plus tard, à l’hôtel.',
  'concept.reply.up-to-you': '« Dedans ou dehors ? » — « Comme vous voulez. »',
  'concept.phrase.good-night': 'Bonne nuit, à demain.',
  'concept.word.cheers': 'Santé ! Au voyage !',
  'concept.reply.nothing-else': 'Rien d’autre, juste le café.',
  'concept.word.congratulations': 'Félicitations !',

  // 🔢 Numbers
  'concept.number.one': 'Un billet, s’il vous plaît.',
  'concept.number.two': 'Une table pour deux.',
  'concept.number.three': 'Trois nuits.',
  'concept.number.ten': 'Un pourboire de dix pour cent.',
  'concept.number.four': 'Quatre personnes.',
  'concept.number.five': 'C’est à cinq minutes.',
  'concept.number.six': 'Chambre six.',
  'concept.number.seven': 'Le petit-déjeuner est à sept heures.',
  'concept.number.eight': 'Porte huit.',
  'concept.number.nine': 'Neuf euros.',
  'concept.number.fifty': 'Ça coûte cinquante.',
  'concept.number.half': 'Neuf heures et demie.',
  'concept.number.twenty': 'Vingt euros, s’il vous plaît.',
  'concept.number.hundred': 'Cent shekels.',
  'concept.number.eleven': 'Le départ est à onze heures.',
  'concept.number.twelve': 'Le déjeuner à midi.',
  'concept.number.thousand': 'Mille personnes étaient là.',

  // 👤 People (pronouns)
  'concept.word.this': 'Ça, s’il vous plaît.',
  'concept.word.i': 'Je voudrais un café.',
  'concept.word.you': 'Vous êtes très aimable.',
  'concept.word.we': 'Nous avons une réservation.',
  'concept.word.my': 'C’est mon sac.',
  'concept.word.that': 'Celui-là, là-bas.',
  'concept.word.it': 'C’est très bon.',
  'concept.word.he': 'Il est avec moi.',
  'concept.word.she': 'Elle parle anglais.',
  'concept.word.they': 'Ils sont avec moi.',
  'concept.word.your': 'Votre passeport, s’il vous plaît.',

  // ❓ Question words
  'concept.word.how': 'Comment aller à la plage ?',
  'concept.word.where': 'Où est la sortie ?',
  'concept.word.when': 'Quand est-ce que ça ouvre ?',
  'concept.word.what': 'C’est quoi ?',
  'concept.phrase.what-time': 'À quelle heure est le départ ?',
  'concept.word.which': 'Quelle porte ?',
  'concept.phrase.how-many': '« Combien de personnes ? » — « Deux. »',
  'concept.phrase.how-long': 'Combien de temps dure le trajet ?',
  'concept.word.who': 'C’est à qui ?',
  'concept.word.why': 'Pourquoi c’est fermé ?',

  // 🕒 Time
  'concept.word.now': 'J’en ai besoin maintenant.',
  'concept.word.today': 'C’est ouvert aujourd’hui ?',
  'concept.word.tomorrow': 'Nous partons demain.',
  'concept.word.later': 'Revenez plus tard.',
  'concept.word.night': 'Deux nuits, s’il vous plaît.',
  'concept.word.day': 'Trois jours dans la ville.',
  'concept.word.hour': 'La visite dure une heure.',
  'concept.word.minute': 'Cinq minutes à pied.',
  'concept.word.time': 'Nous n’avons pas le temps.',
  'concept.word.morning': 'Demain matin à huit heures.',
  'concept.word.late': 'Le bus est en retard.',
  'concept.word.evening': 'Une table pour ce soir.',
  'concept.word.week': 'Une semaine en Italie.',
  'concept.word.yesterday': 'Nous sommes arrivés hier.',
  'concept.word.early': 'Nous sommes arrivés tôt.',
  'concept.word.soon': 'Le train arrive bientôt.',
  'concept.word.afternoon': 'Fermé l’après-midi.',
  'concept.word.year': 'Bonne année !',
  'concept.word.month': 'Le mois prochain.',
  'concept.word.always': 'C’est toujours ouvert.',
  'concept.word.never': 'Je ne mange jamais de viande.',
  'concept.word.weekend': 'Fermé le week-end.',
  'concept.word.monday': 'Fermé le lundi.',
  'concept.word.friday': 'Vendredi soir.',
  'concept.word.sunday': 'Tout est fermé le dimanche.',
  'concept.word.saturday': 'Ouvert le samedi ?',
  'concept.word.tuesday': 'Le marché est le mardi.',
  'concept.word.wednesday': 'Nous prenons l’avion mercredi.',
  'concept.word.thursday': 'Jusqu’à jeudi.',
};

