/**
 * Spanish Foundation example sentences — AUTHORED Spanish, one per Foundation building-block concept.
 *
 * The Core Corpus stores examples per concept in en+he only, so a Spanish learner would otherwise see
 * an English example on a Foundation word page (immersion-breaking). Each entry here is the SPANISH
 * translation of that concept's canonical example, so the corpus Hebrew (`example.he`) stays aligned
 * as the "underneath" line and the word page reads: Spanish first · Hebrew under · Spanish audio.
 *
 * Keyed by language-independent concept id (works for the tapped word and the browsed word alike).
 * AI-drafted, neutral international Spanish (usted for service), `pending native review` — consistent
 * with the Spanish Bootcamp.
 *
 * This file is pure CONTENT (a Spanish map). The language-agnostic accessor lives in
 * `foundationExamples.ts`, which registers this map under `es` — so adding another language's
 * examples is content-only, with no per-language code branch. When a concept has no entry, the app
 * shows the app-language meaning (never English-as-Spanish).
 */
export const SPANISH_EXAMPLES: Record<string, string> = {
  // ⚡ Essential verbs
  'concept.word.help': '¿Puede ayudarme?',
  'concept.word.stop': 'Pare aquí, por favor.',
  'concept.word.lose': 'He perdido mi pasaporte.',
  'concept.word.want': 'Quiero este.',
  'concept.word.need': 'Necesito ayuda.',
  'concept.word.have': 'Tengo una reserva.',
  'concept.word.go': 'Vamos al aeropuerto.',
  'concept.word.speak': '¿Habla inglés?',
  'concept.word.pay': '¿Puedo pagar con tarjeta?',
  'concept.word.understand': 'Ahora entiendo.',
  'concept.word.eat': '¿Dónde se puede comer?',
  'concept.word.can': '¿Puede ayudarme?',
  'concept.word.order': '¿Está listo para pedir?',
  'concept.word.wait': 'Espere aquí, por favor.',
  'concept.word.show': '¿Me lo puede mostrar?',
  'concept.word.turn': 'Gire a la izquierda en la esquina.',
  'concept.word.take': 'Me lo llevo.',
  'concept.word.buy': '¿Dónde puedo comprar entradas?',
  'concept.word.come': 'Venga conmigo, por favor.',
  'concept.word.call': 'Llame a un taxi, por favor.',
  'concept.word.find': 'No encuentro mi hotel.',
  'concept.word.leave': 'El tren sale a las nueve.',
  'concept.word.book': 'He reservado una habitación.',
  'concept.word.arrive': '¿Cuándo llega?',
  'concept.word.drink': '¿Algo de beber?',
  'concept.word.know': '¿Conoce un buen sitio?',
  'concept.word.give': 'Deme uno, por favor.',
  'concept.word.work': 'La ducha no funciona.',
  'concept.word.cancel': 'Quiero cancelar el pedido.',
  'concept.word.fly': 'Volamos el domingo.',
  'concept.word.rent': 'Queremos alquilar un auto.',
  'concept.word.exchange': '¿Dónde puedo cambiar dinero?',
  'concept.word.forget': 'He olvidado mi llave.',
  'concept.word.break': 'Está roto.',
  'concept.word.smoke': 'Prohibido fumar aquí.',
  'concept.word.stay': 'Nos quedamos tres noches.',
  'concept.word.see': 'Quisiera ver la carta.',
  'concept.word.look': '¡Mire eso!',
  'concept.word.say': '¿Cómo se dice esto?',
  'concept.word.like': 'Me gusta este sitio.',
  'concept.word.get': '¿Dónde se toma el autobús?',
  'concept.word.ask': 'Preguntemos a alguien.',
  'concept.word.use': '¿Puedo usar el teléfono?',
  'concept.word.return': 'Volvemos mañana.',
  'concept.word.push': 'Empuje la puerta.',
  'concept.word.pull': 'Tire, no empuje.',
  'concept.word.sit': '¿Podemos sentarnos fuera?',
  'concept.word.try': '¿Me lo puedo probar?',
  'concept.word.love': 'Me encanta esta ciudad.',
  'concept.word.bring': '¿Me puede traer la cuenta?',
  'concept.word.visit': 'Queremos visitar el casco antiguo.',
  'concept.word.travel': 'Viajamos mucho.',
  'concept.word.think': 'Creo que está cerca.',
  'concept.word.hear': 'No le oigo.',
  'concept.word.sleep': 'Necesito dormir.',
  'concept.word.answer': 'No contesta nadie.',
  'concept.word.remember': 'No recuerdo el nombre.',
  'concept.word.send': 'Envíeme la dirección.',
  'concept.word.drive': 'Maneja despacio.',
  'concept.word.meet': 'Encantado de conocerle.',
  'concept.word.stand': 'Haga cola, por favor.',
  'concept.word.wash': '¿Dónde puedo lavarme las manos?',

  // 🎨 Colors
  'concept.word.red': 'El autobús rojo.',
  'concept.word.blue': 'La línea azul.',
  'concept.word.green': 'Cruce en verde.',
  'concept.word.black': 'Un café solo, por favor.',
  'concept.word.white': 'Vino blanco.',
  'concept.word.pink': 'El vestido rosa.',
  'concept.word.yellow': 'El taxi amarillo.',
  'concept.word.orange': 'El edificio naranja.',
  'concept.word.brown': 'El bolso marrón.',
  'concept.word.purple': 'La línea morada.',

  // 📏 Quantity
  'concept.word.more': 'Un poco más, por favor.',
  'concept.word.full': 'El hotel está completo.',
  'concept.word.less': 'Un poco menos, por favor.',
  'concept.word.empty': 'El autobús está vacío.',

  // 📍 Position & Direction
  'concept.word.here': 'Pare aquí, por favor.',
  'concept.word.left': 'Está a la izquierda.',
  'concept.word.right': 'Gire a la derecha.',
  'concept.word.there': 'Está allí.',
  'concept.word.up': 'La habitación está subiendo las escaleras.',
  'concept.word.down': 'El desayuno está abajo.',

  // 🔗 Connectors & ✅ Quick responses (glue)
  'concept.word.yes': 'Sí, por favor.',
  'concept.word.no': 'No, gracias.',
  'concept.word.please': 'Un boleto, por favor.',
  'concept.word.okay': 'De acuerdo, no hay problema.',
  'concept.word.hello': '¡Hola! ¿Una mesa para dos?',
  'concept.reply.here-you-go': '«Aquí tiene.» — «¡Gracias!»',
  'concept.phrase.excuse-me': 'Perdone, ¿dónde está la salida?',
  'concept.word.with': 'Un café con leche.',
  'concept.word.and': 'Un café y agua.',
  'concept.word.or': '¿Efectivo o tarjeta?',
  'concept.word.without': 'Un té sin azúcar.',
  'concept.reply.i-dont-know': 'No lo sé. Preguntemos.',
  'concept.word.goodbye': '¡Adiós, y gracias!',
  'concept.reply.sounds-good': '«¿Pizza esta noche?» — «¡Me parece bien!»',
  'concept.reply.no-worries': '«Perdón, llegamos tarde.» — «No se preocupe.»',
  'concept.reply.thats-fine': '«Solo tarjeta, no efectivo.» — «Está bien.»',
  'concept.reply.no-problem': '«¿Podemos pagar por separado?» — «No hay problema.»',
  'concept.reply.never-mind': 'No importa, gracias de todos modos.',
  'concept.reply.im-not-sure': 'No estoy seguro. Quizás a las nueve.',
  'concept.reply.thats-all': '«¿Algo más?» — «Eso es todo, gracias.»',
  'concept.reply.one-more': 'Uno más, por favor. Estaba muy bueno.',
  'concept.word.enough': 'Es suficiente, gracias.',
  'concept.reply.just-looking': '«¿Le ayudo?» — «Solo estoy mirando.»',
  'concept.reply.to-go': 'Un café para llevar, por favor.',
  'concept.word.great': '¡Genial, gracias!',
  'concept.reply.youre-welcome': '«¡Gracias!» — «De nada.»',
  'concept.reply.of-course': '«¿Puedo sentarme aquí?» — «Por supuesto.»',
  'concept.reply.have-a-nice-day': '«¡Que tenga un buen día!» — «¡Igualmente!»',
  'concept.phrase.good-morning': '¡Buenos días! El desayuno, por favor.',
  'concept.reply.lets-go': 'El taxi está aquí. ¡Vamos!',
  'concept.phrase.good-evening': '¡Buenas tardes! Tenemos una reserva.',
  'concept.reply.maybe-later': '«¿Un postre?» — «Quizás más tarde.»',
  'concept.reply.go-ahead': '«¿Puedo preguntar una cosa?» — «Adelante.»',
  'concept.word.really': '¿De verdad? ¡Es genial!',
  'concept.reply.take-your-time': '«Un momento…» — «Tómese su tiempo.»',
  'concept.reply.me-too': '«Me encanta esta ciudad.» — «¡Yo también!»',
  'concept.reply.and-you': 'Estoy bien. ¿Y usted?',
  'concept.reply.see-you-later': 'Hasta luego, en el hotel.',
  'concept.reply.up-to-you': '«¿Dentro o fuera?» — «Como usted quiera.»',
  'concept.phrase.good-night': 'Buenas noches, hasta mañana.',
  'concept.word.cheers': '¡Salud! ¡Por el viaje!',
  'concept.reply.nothing-else': 'Nada más, solo el café.',
  'concept.word.congratulations': '¡Felicidades!',

  // 🔢 Numbers
  'concept.number.one': 'Un boleto, por favor.',
  'concept.number.two': 'Una mesa para dos.',
  'concept.number.three': 'Tres noches.',
  'concept.number.ten': 'Una propina del diez por ciento.',
  'concept.number.four': 'Cuatro personas.',
  'concept.number.five': 'Está a cinco minutos.',
  'concept.number.six': 'Habitación seis.',
  'concept.number.seven': 'El desayuno es a las siete.',
  'concept.number.eight': 'Puerta ocho.',
  'concept.number.nine': 'Nueve euros.',
  'concept.number.fifty': 'Cuesta cincuenta.',
  'concept.number.half': 'Las nueve y media.',
  'concept.number.twenty': 'Veinte euros, por favor.',
  'concept.number.hundred': 'Cien shekels.',
  'concept.number.eleven': 'La salida es a las once.',
  'concept.number.twelve': 'El almuerzo a las doce.',
  'concept.number.thousand': 'Había mil personas.',

  // 👤 People (pronouns)
  'concept.word.this': 'Esto, por favor.',
  'concept.word.i': 'Quisiera un café.',
  'concept.word.you': 'Es usted muy amable.',
  'concept.word.we': 'Tenemos una reserva.',
  'concept.word.my': 'Es mi bolsa.',
  'concept.word.that': 'Ese, el de allí.',
  'concept.word.it': 'Está muy bueno.',
  'concept.word.he': 'Él está conmigo.',
  'concept.word.she': 'Ella habla inglés.',
  'concept.word.they': 'Ellos están conmigo.',
  'concept.word.your': 'Su pasaporte, por favor.',

  // ❓ Question words
  'concept.word.how': '¿Cómo se llega a la playa?',
  'concept.word.where': '¿Dónde está la salida?',
  'concept.word.when': '¿Cuándo abre?',
  'concept.word.what': '¿Qué es esto?',
  'concept.phrase.what-time': '¿A qué hora es la salida?',
  'concept.word.which': '¿Qué puerta?',
  'concept.phrase.how-many': '«¿Cuántas personas?» — «Dos.»',
  'concept.phrase.how-long': '¿Cuánto dura el trayecto?',
  'concept.word.who': '¿De quién es esto?',
  'concept.word.why': '¿Por qué está cerrado?',

  // 🕒 Time
  'concept.word.now': 'Lo necesito ahora.',
  'concept.word.today': '¿Está abierto hoy?',
  'concept.word.tomorrow': 'Salimos mañana.',
  'concept.word.later': 'Vuelva más tarde.',
  'concept.word.night': 'Dos noches, por favor.',
  'concept.word.day': 'Tres días en la ciudad.',
  'concept.word.hour': 'La visita dura una hora.',
  'concept.word.minute': 'Cinco minutos a pie.',
  'concept.word.time': 'No tenemos tiempo.',
  'concept.word.morning': 'Mañana por la mañana a las ocho.',
  'concept.word.late': 'El autobús llega tarde.',
  'concept.word.evening': 'Una mesa para esta noche.',
  'concept.word.week': 'Una semana en Italia.',
  'concept.word.yesterday': 'Llegamos ayer.',
  'concept.word.early': 'Llegamos temprano.',
  'concept.word.soon': 'El tren llega pronto.',
  'concept.word.afternoon': 'Cerrado por la tarde.',
  'concept.word.year': '¡Feliz año!',
  'concept.word.month': 'El mes que viene.',
  'concept.word.always': 'Siempre está abierto.',
  'concept.word.never': 'Nunca como carne.',
  'concept.word.weekend': 'Cerrado el fin de semana.',
  'concept.word.monday': 'Cerrado los lunes.',
  'concept.word.friday': 'El viernes por la noche.',
  'concept.word.sunday': 'Los domingos todo está cerrado.',
  'concept.word.saturday': '¿Abren los sábados?',
  'concept.word.tuesday': 'El mercado es los martes.',
  'concept.word.wednesday': 'Volamos el miércoles.',
  'concept.word.thursday': 'Hasta el jueves.',
};
