import type { LocalizedText } from '@ready/content-schema';

/**
 * French number construction (0–9999) — the ONE source of truth for spoken `fr-FR` numbers, so the
 * hard patterns (`soixante-dix`, `quatre-vingts`, `quatre-vingt-dix`) are generated by a tested rule,
 * never hand-copied. English numbers reuse the Core Corpus atoms; French cannot — 70/80/90 are
 * compositional in a way English isn't, and that irregularity is exactly what a traveler must learn.
 *
 * Spelling rules encoded (Part 6):
 *  - `et` joins the unit 1 (and 11 at 71): vingt et un, trente et un … soixante et onze — but NOT
 *    quatre-vingt-un / quatre-vingt-onze (no `et` in the 80s/90s).
 *  - `quatre-vingts` takes a final -s only when it ends the number exactly (80); quatre-vingt-un,
 *    quatre-vingt-cinq have no -s.
 *  - `cent` pluralises to `cents` for an exact multiple (deux cents) but not when followed
 *    (deux cent un); `mille` is invariable.
 *  - hyphenation follows the modern (1990) convention within compound tens/units.
 *
 * HONESTY: research-plausible, `fr-FR` register, pending native review.
 */

const UNITS = ['zéro', 'un', 'deux', 'trois', 'quatre', 'cinq', 'six', 'sept', 'huit', 'neuf',
  'dix', 'onze', 'douze', 'treize', 'quatorze', 'quinze', 'seize', 'dix-sept', 'dix-huit', 'dix-neuf'];
const TENS: Record<number, string> = { 20: 'vingt', 30: 'trente', 40: 'quarante', 50: 'cinquante', 60: 'soixante' };

/** Spoken French for 0–99. Handles the 70/80/90 vigesimal patterns and the `et`/-s rules. */
function belowHundred(n: number): string {
  if (n < 20) return UNITS[n]!;
  if (n < 70) {
    const t = Math.floor(n / 10) * 10;
    const u = n % 10;
    if (u === 0) return TENS[t]!;
    if (u === 1) return `${TENS[t]} et un`;
    return `${TENS[t]}-${UNITS[u]}`;
  }
  // 70–79: soixante + (10..19) → soixante-dix, soixante et onze, soixante-douze …
  if (n < 80) {
    const rest = n - 60; // 10..19
    if (rest === 11) return 'soixante et onze';
    return `soixante-${UNITS[rest]}`;
  }
  // 80–99: quatre-vingt(s) + (0..19)
  const rest = n - 80; // 0..19
  if (rest === 0) return 'quatre-vingts';       // exact 80 keeps the -s
  return `quatre-vingt-${UNITS[rest]}`;          // 81+ drop the -s and never take `et`
}

/** Spoken French for a non-negative integer (0–9999 covers every travel need: prices, rooms, years). */
export function frenchNumber(n: number): string {
  if (!Number.isInteger(n) || n < 0) throw new Error(`frenchNumber: unsupported ${n}`);
  if (n < 100) return belowHundred(n);
  if (n < 1000) {
    const h = Math.floor(n / 100);
    const rest = n % 100;
    const hundreds = h === 1 ? 'cent' : `${UNITS[h]} cent`;
    if (rest === 0) return h === 1 ? 'cent' : `${UNITS[h]} cents`; // deux cents, but cent un / deux cent un below
    return `${hundreds} ${belowHundred(rest)}`;
  }
  const th = Math.floor(n / 1000);
  const rest = n % 1000;
  const thousands = th === 1 ? 'mille' : `${frenchNumber(th)} mille`; // mille is invariable
  return rest === 0 ? thousands : `${thousands} ${frenchNumber(rest)}`;
}

/** One drilled number: value + French + glosses (+ optional teaching note about the pattern). */
export interface FrNumberDrill {
  value: number;
  fr: string;
  meaning: LocalizedText;
  note?: LocalizedText;
}

const T = (he: string, en: string): LocalizedText => ({ he, en });

/** The irregular forms a traveler MUST recognise — the ones English intuition gets wrong. */
export const FR_TRICKY_NUMBERS: FrNumberDrill[] = [
  { value: 70, fr: frenchNumber(70), meaning: T('שבעים', 'seventy'), note: T('60 + 10 = "שישים-עשר".', 'literally sixty-ten.') },
  { value: 71, fr: frenchNumber(71), meaning: T('שבעים ואחת', 'seventy-one'), note: T('60 ו-11, עם "et".', 'sixty-and-eleven, with "et".') },
  { value: 80, fr: frenchNumber(80), meaning: T('שמונים', 'eighty'), note: T('4×20, עם s בסוף.', 'four-twenties — takes a final -s.') },
  { value: 81, fr: frenchNumber(81), meaning: T('שמונים ואחת', 'eighty-one'), note: T('בלי s ובלי "et".', 'no -s and no "et".') },
  { value: 90, fr: frenchNumber(90), meaning: T('תשעים', 'ninety'), note: T('4×20 + 10.', 'four-twenties-ten.') },
  { value: 91, fr: frenchNumber(91), meaning: T('תשעים ואחת', 'ninety-one'), note: T('4×20 + 11, בלי "et".', 'four-twenties-eleven, no "et".') },
  { value: 99, fr: frenchNumber(99), meaning: T('תשעים ותשע', 'ninety-nine') },
  { value: 100, fr: frenchNumber(100), meaning: T('מאה', 'one hundred') },
  { value: 1000, fr: frenchNumber(1000), meaning: T('אלף', 'one thousand') },
];

/** Common spoken prices a traveler hears — numbers connected to the paying situation (Part 7). */
export const FR_PRICE_EXAMPLES: FrNumberDrill[] = [7, 15, 20, 25, 70, 80, 90, 95].map((v) => ({
  value: v,
  fr: `${frenchNumber(v)} euros`,
  meaning: T(`${v} יורו`, `${v} euros`),
}));
